# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b1fdf3733bcb43f0734ecc10554faee570feb00a7cb284d804e7bccf22b0f422fe90de9be0dfd7daa4273b400633d4191f72f4017569b84e74e35ffdf01560

test:
  secret_key_base: 74f7da5b11cb373d1749007588d6fd58bf48aea6fae8542799d0a228854726e5dfa3e63c778e666fddb802c9b3bb9f660b86cd9f43f55092ec236e3e9361897b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
